name: Steam Stats
on:
  create:
  schedule:
    - cron: "* */1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Profile and detailed game history
    steps:
      - uses: actions/checkout@master
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.steam.full.svg
          token: NOT_NEEDED
          base: ""
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: ${{ secrets.STEAM_ID }}
          plugin_steam_games_limit: 3
